
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import DatabaseClass.DBOperation;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author alhaanahmed
 */
public class Menu extends javax.swing.JFrame {
    /**
     * Creates new form Menu
     */
    DBOperation dbconnect;
    private DefaultTableModel tableModel;
    public Menu() {
        initComponents();
        tableModel = (DefaultTableModel) tableToDisplayCars.getModel();
        getdbData();
      
    }
    
    public void getdbData() {
          try {
            Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/carapp","root","devsync123@Alhaan");
            Statement st = connection.createStatement();
            ResultSet rs = st.executeQuery("select * from cars");
            
            tableModel.setRowCount(0);
            
            while (rs.next()) {
                Object[] data = {
                    rs.getInt("car_id"),
                    rs.getString("carName"),
                    rs.getString("carModel"),
                    rs.getString("carMake"),
                    rs.getInt("carYear"),
                    rs.getInt("carPrice")
   
                };
                tableModel.addRow(data);
            }
            
            rs.close();
            st.close();
            connection.close();
        }
        catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        signoutLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        labelForcarStatus = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableToDisplayCars = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        carMakeField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        carNameField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        carModelField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        carYearField = new javax.swing.JTextField();
        carPriceField = new javax.swing.JTextField();
        removeCarbtn = new javax.swing.JButton();
        addCarBtn = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 681, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Car Management App");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));

        signoutLabel.setFont(new java.awt.Font("FreeSans", 1, 13)); // NOI18N
        signoutLabel.setForeground(new java.awt.Color(255, 255, 255));
        signoutLabel.setText("Sign Out");
        signoutLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        signoutLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                signoutLabelMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("FreeSans", 1, 13)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Get Help?");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(signoutLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(signoutLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setForeground(new java.awt.Color(0, 0, 0));

        labelForcarStatus.setFont(new java.awt.Font("FreeSans", 1, 18)); // NOI18N
        labelForcarStatus.setForeground(new java.awt.Color(0, 0, 0));
        labelForcarStatus.setText("Car Status available in Showroom");

        tableToDisplayCars.setBackground(new java.awt.Color(0, 51, 51));
        tableToDisplayCars.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 204)));
        tableToDisplayCars.setFont(new java.awt.Font("FreeSans", 0, 13)); // NOI18N
        tableToDisplayCars.setForeground(new java.awt.Color(255, 255, 255));
        tableToDisplayCars.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, "", null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Model", "Make", "Year", "Price"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableToDisplayCars);

        jLabel1.setFont(new java.awt.Font("FreeSans", 1, 13)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Enter Car Name:");

        carMakeField.setBackground(new java.awt.Color(51, 51, 51));
        carMakeField.setForeground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("FreeSans", 1, 13)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Car Model No:");

        carNameField.setBackground(new java.awt.Color(51, 51, 51));
        carNameField.setForeground(new java.awt.Color(255, 255, 255));

        jLabel4.setFont(new java.awt.Font("FreeSans", 1, 13)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Company Name:");

        carModelField.setBackground(new java.awt.Color(51, 51, 51));
        carModelField.setForeground(new java.awt.Color(255, 255, 255));

        jLabel5.setFont(new java.awt.Font("FreeSans", 1, 13)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Year");

        jLabel6.setFont(new java.awt.Font("FreeSans", 1, 13)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Price");

        carYearField.setBackground(new java.awt.Color(51, 51, 51));
        carYearField.setForeground(new java.awt.Color(255, 255, 255));
        carYearField.setText("\n");

        carPriceField.setBackground(new java.awt.Color(51, 51, 51));
        carPriceField.setForeground(new java.awt.Color(255, 255, 255));

        removeCarbtn.setBackground(new java.awt.Color(255, 0, 0));
        removeCarbtn.setFont(new java.awt.Font("FreeSans", 1, 13)); // NOI18N
        removeCarbtn.setForeground(new java.awt.Color(255, 255, 255));
        removeCarbtn.setText("Remove Car");
        removeCarbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeCarbtnActionPerformed(evt);
            }
        });

        addCarBtn.setBackground(new java.awt.Color(0, 102, 102));
        addCarBtn.setFont(new java.awt.Font("FreeSans", 1, 13)); // NOI18N
        addCarBtn.setForeground(new java.awt.Color(255, 255, 255));
        addCarBtn.setText("Add Car");
        addCarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCarBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(labelForcarStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(carNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(addCarBtn))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(carModelField, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                                    .addComponent(carMakeField, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                                    .addComponent(removeCarbtn)
                                    .addComponent(carYearField)
                                    .addComponent(carPriceField)))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(169, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelForcarStatus)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(carNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLabel3))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(carModelField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(carMakeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(7, 7, 7)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(carYearField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(carPriceField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(removeCarbtn)
                    .addComponent(addCarBtn))
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void signoutLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signoutLabelMouseClicked
        // TODO add your handling code here:
        int option = JOptionPane.showConfirmDialog(null, "Do you want to Log out", "Log Out Session", JOptionPane.YES_NO_CANCEL_OPTION);
        // Select the Options according to condition
        switch (option) {
            case JOptionPane.YES_OPTION:
                this.dispose();
                break;
            case JOptionPane.CANCEL_OPTION:
            case JOptionPane.NO_OPTION:
                this.setVisible(true);
                break;
            default:
                JOptionPane.showMessageDialog(null, "Select something!!");
                break;
        }
    }//GEN-LAST:event_signoutLabelMouseClicked

    private void removeCarbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeCarbtnActionPerformed
        // TODO add your handling code here:
         try {
        int selectedRow = tableToDisplayCars.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Please select a car to remove.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Get the car ID from the selected row
        int carId = (int) tableModel.getValueAt(selectedRow, 0);

        DBOperation dbOperation = new DBOperation();
        Connection connection = dbOperation.connectDB();

        // Prepare the SQL statement
        String sql = "DELETE FROM cars WHERE car_id = ?";
        try (PreparedStatement preparedStatement = connection.prepareStatement(sql)) {
            preparedStatement.setInt(1, carId);

            // Execute the SQL statement
            preparedStatement.executeUpdate();
        }

        // Refresh the table data after removal
        getdbData();

        // Close the database connection
        dbOperation.closeConnection(connection);

    } catch (Exception ex) {
        Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_removeCarbtnActionPerformed

    private void addCarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCarBtnActionPerformed
        String carName = carNameField.getText();
        String carModel = carModelField.getText();
        String carMake = carMakeField.getText();
        int carYear = Integer.parseInt(carYearField.getText().trim());
        int carPrice = Integer.parseInt(carPriceField.getText());
        
        try {
            DBOperation dbOperation = new DBOperation();
            Connection connection = dbOperation.connectDB();
            PreparedStatement statement = connection.prepareStatement("insert into cars(carName, carMake, carModel, carYear, carPrice) values(?,?,?,?,?)");
            try {
            statement.setString(1, carName);
            statement.setString(2, carModel);
            statement.setString(3, carMake);
            statement.setInt(4, carYear);
            statement.setInt(5, carPrice);

           
            statement.executeUpdate();
      
            getdbData();
            }
            catch (NumberFormatException ex) {
                ex.printStackTrace();
                JOptionPane.showMessageDialog(null, "Error adding number");
            }
            
        
            dbOperation.closeConnection(connection);
    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(null, ex);
    }
       
        
    }//GEN-LAST:event_addCarBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addCarBtn;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JTextField carMakeField;
    private javax.swing.JTextField carModelField;
    private javax.swing.JTextField carNameField;
    private javax.swing.JTextField carPriceField;
    private javax.swing.JTextField carYearField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelForcarStatus;
    private javax.swing.JButton removeCarbtn;
    private javax.swing.JLabel signoutLabel;
    private javax.swing.JTable tableToDisplayCars;
    // End of variables declaration//GEN-END:variables
}
